### ISSUE TITLE
env does not work

### ISSUE THREAD

**Issue by LEW21** [SamSaffron/pups#4]
YAML file:

```
env:
  MY_VAR: 'some value'

run:
  - exec:
      cmd:
        - "echo $MY_VAR"
```

Expected result:

```
# /pups/bin/pups test.yaml
I, [2014-07-14T12:32:17.000031 #827]  INFO -- : Loading test.yaml
I, [2014-07-14T12:32:17.000855 #827]  INFO -- : > echo $MY_VAR
I, [2014-07-14T12:32:17.001899 #827]  INFO -- : some value
```

Actual result:

```
# /pups/bin/pups test.yaml
I, [2014-07-14T12:32:17.000031 #827]  INFO -- : Loading test.yaml
I, [2014-07-14T12:32:17.000855 #827]  INFO -- : > echo $MY_VAR
I, [2014-07-14T12:32:17.001899 #827]  INFO -- : 
```
